const videos=[
{id:'dQw4w9WgXcQ',title:'The art of starting before you feel ready',creator:'Maya Chen',channel:'The Slow Down',views:'2.4M views',date:'3 days ago',duration:'12:48',category:'Design',description:'A thoughtful field guide to making space for better work, better ideas, and a little more courage.',avatar:'https://i.pravatar.cc/80?img=47',thumb:'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=900&q=80'},
{id:'9bZkp7q19s4',title:'I built a tiny house in the mountains',creator:'Noah Williams',channel:'Field Notes',views:'891K views',date:'1 week ago',duration:'18:21',category:'Travel',description:'One year, one empty plot, and a lot of lessons about building a life with less noise.',avatar:'https://i.pravatar.cc/80?img=12',thumb:'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=900&q=80'},
{id:'5JnMutdy6Yw',title:'The future of AI is more human than you think',creator:'Ari Patel',channel:'Signal / Noise',views:'1.1M views',date:'5 days ago',duration:'24:05',category:'Technology',description:'A clear, optimistic look at the tools changing how we create, work, and connect.',avatar:'https://i.pravatar.cc/80?img=32',thumb:'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80'},
{id:'kJQP7kiw5Fk',title:'How I plan my week without burning out',creator:'Lena Ortiz',channel:'Sunday Studio',views:'430K views',date:'2 weeks ago',duration:'09:42',category:'Wellness',description:'A gentle weekly reset for people who want to do meaningful work without running on empty.',avatar:'https://i.pravatar.cc/80?img=49',thumb:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80'},
{id:'3PHXvlpOkf4',title:'Tokyo at 5am: a quiet city guide',creator:'Kenji Watanabe',channel:'After Hours',views:'678K views',date:'4 days ago',duration:'15:16',category:'Travel',description:'The city before the crowds: coffee, train lines, and the best light in Tokyo.',avatar:'https://i.pravatar.cc/80?img=11',thumb:'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=900&q=80'},
{id:'F9UG9XX9FIA',title:'The playlist that changed my year',creator:'Nia Rivers',channel:'Good Company',views:'2.8M views',date:'1 month ago',duration:'31:08',category:'Music',description:'Twenty songs, five memories, and one very good year in review.',avatar:'https://i.pravatar.cc/80?img=44',thumb:'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=900&q=80'},
{id:'mFQP7N2pE4g',title:'A practical guide to making things beautiful',creator:'Studio Forma',channel:'Studio Forma',views:'944K views',date:'6 days ago',duration:'20:10',category:'Design',description:'The small decisions that make a big difference in product, space, and visual design.',avatar:'https://i.pravatar.cc/80?img=5',thumb:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=80'},
{id:'Hzevd8l3x7M',title:'Why everyone is talking about indie games',creator:'Pixel Common',channel:'Pixel Common',views:'1.7M views',date:'3 weeks ago',duration:'14:33',category:'Gaming',description:'The tiny teams, big ideas, and strange new worlds behind the indie game renaissance.',avatar:'https://i.pravatar.cc/80?img=68',thumb:'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=900&q=80'}
];
const categories=['All','Music','Mixes','Live','Gaming','News','Technology','Design','Travel','Recently uploaded'];
const state={section:'home',category:'All',query:'',liked:false,subscribed:false,visible:8};
const $=id=>document.getElementById(id);
function renderCategories(){ $('categoryRow').innerHTML=categories.map(c=>`<button class="category-btn ${state.category===c?'active':''}" data-category="${c}">${c}</button>`).join('');document.querySelectorAll('[data-category]').forEach(button=>button.addEventListener('click',()=>{state.category=button.dataset.category;renderCategories();renderVideos()})); }
function filtered(){let list=[...videos];if(state.category!=='All'&&state.category!=='Recently uploaded')list=list.filter(v=>v.category===state.category||state.category==='Mixes');if(state.query)list=list.filter(v=>(v.title+' '+v.creator+' '+v.channel+' '+v.category).toLowerCase().includes(state.query.toLowerCase()));return list;}
function renderVideos(){const list=filtered().slice(0,state.visible);$('videoGrid').innerHTML=list.length?list.map(v=>`<article class="video-card" data-video="${v.id}"><div class="thumbnail"><img loading="lazy" src="${v.thumb}" alt="${v.title}"><span class="duration">${v.duration}</span></div><div class="video-details"><img class="creator-avatar" src="${v.avatar}" alt="${v.channel} avatar"><div><h3 class="video-title">${v.title}</h3><span class="channel-name">${v.channel} <i class="fas fa-check-circle" aria-label="Verified"></i></span><span class="video-meta">${v.views} · ${v.date}</span></div></div></article>`).join(''):`<div class="empty-state"><h3>No videos found</h3><p>Try another search or topic.</p></div>`;document.querySelectorAll('.video-card').forEach(card=>card.addEventListener('click',()=>openPlayer(videos.find(video=>video.id===card.dataset.video))));$('loadMore').style.display=list.length>=state.visible?'block':'none';}
function toast(message){const element=$('toast');element.textContent=message;element.classList.add('show');window.clearTimeout(window.toastTimer);window.toastTimer=window.setTimeout(()=>element.classList.remove('show'),2200)}
function openPlayer(video){if(!video)return;$('videoFrame').src=`https://www.youtube.com/embed/${video.id}?autoplay=1&rel=0`;$('playerTitle').textContent=video.title;$('playerStats').textContent=`${video.channel} · ${video.views} · ${video.date}`;$('playerDescription').textContent=video.description;$('playerModal').classList.add('active');$('playerModal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closePlayer(){$('videoFrame').src='';$('playerModal').classList.remove('active');$('playerModal').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function setSection(section){state.section=section;document.querySelectorAll('.nav-item,.mobile-nav-item').forEach(item=>item.classList.toggle('active',item.dataset.section===section));const titles={home:['Recommended','Home'],shorts:['Quick hits','Shorts'],subscriptions:['From your channels','Subscriptions'],history:['Keep watching','History'],liked:['Your favorites','Liked videos'],'watch-later':['Saved for later','Watch later'],music:['Listen now','Music'],gaming:['Press play','Gaming'],live:['Happening now','Live'],library:['Your collection','Library']};const [kicker,title]=titles[section]||titles.home;$('sectionKicker').textContent=kicker;$('sectionTitle').textContent=title;$('heroBanner').style.display=section==='home'?'flex':'none';state.category=['music','gaming','live'].includes(section)?section[0].toUpperCase()+section.slice(1):'All';if(!categories.includes(state.category))state.category='All';renderCategories();renderVideos();$('sidebar').classList.remove('open');$('overlay').classList.remove('open')}
function search(){state.query=$('searchInput').value.trim();state.section='home';document.querySelectorAll('.nav-item,.mobile-nav-item').forEach(item=>item.classList.toggle('active',item.dataset.section==='home'));$('suggestions').hidden=true;$('sectionKicker').textContent=state.query?'Search results':'Recommended';$('sectionTitle').textContent=state.query?`Results for “${state.query}”`:'Home';$('heroBanner').style.display=state.query?'none':'flex';renderVideos()}
$('searchForm').addEventListener('submit',event=>{event.preventDefault();search()});$('searchInput').addEventListener('input',event=>{const query=event.target.value.trim().toLowerCase();if(!query){$('suggestions').hidden=true;return}const matches=videos.filter(video=>(video.title+' '+video.creator+' '+video.channel).toLowerCase().includes(query)).slice(0,5);$('suggestions').innerHTML=matches.map(video=>`<button class="suggestion" data-suggest="${video.title}"><i class="fas fa-magnifying-glass"></i> ${video.title}</button>`).join('');$('suggestions').hidden=!matches.length;document.querySelectorAll('[data-suggest]').forEach(button=>button.addEventListener('click',()=>{$('searchInput').value=button.dataset.suggest;search()}))});
$('menuBtn').addEventListener('click',()=>{$('sidebar').classList.toggle('open');$('overlay').classList.toggle('open')});$('overlay').addEventListener('click',()=>{$('sidebar').classList.remove('open');$('overlay').classList.remove('open')});$('closePlayer').addEventListener('click',closePlayer);$('playerModal').addEventListener('click',event=>{if(event.target===$('playerModal'))closePlayer()});document.addEventListener('keydown',event=>{if(event.key==='Escape'){closePlayer();$('suggestions').hidden=true}});document.querySelectorAll('.nav-item,.mobile-nav-item').forEach(item=>item.addEventListener('click',()=>setSection(item.dataset.section)));$('brand').addEventListener('click',()=>setSection('home'));$('heroBtn').addEventListener('click',()=>{$('sectionTitle').scrollIntoView({behavior:'smooth'})});$('viewAllBtn').addEventListener('click',()=>{$('videoGrid').scrollIntoView({behavior:'smooth'})});$('loadMore').addEventListener('click',()=>{state.visible+=4;renderVideos();toast('More videos loaded')});$('playerSubscribe').addEventListener('click',()=>{state.subscribed=!state.subscribed;$('playerSubscribe').textContent=state.subscribed?'Subscribed':'Subscribe';toast(state.subscribed?'You are now subscribed':'Subscription removed')});$('likeBtn').addEventListener('click',()=>{state.liked=!state.liked;$('likeBtn').classList.toggle('liked',state.liked);$('likeBtn').innerHTML=state.liked?'<i class="fas fa-thumbs-up"></i><span>Liked</span>':'<i class="far fa-thumbs-up"></i><span>Like</span>';toast(state.liked?'Added to liked videos':'Removed from liked videos')});$('saveBtn').addEventListener('click',()=>toast('Saved to Watch later'));$('shareBtn').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(window.location.href);toast('Link copied')}catch(error){toast('Share link ready')}});$('createBtn').addEventListener('click',()=>toast('Create menu opened'));$('notificationBtn').addEventListener('click',()=>toast('No new notifications'));$('profileBtn').addEventListener('click',()=>toast('Account menu opened'));
renderCategories();renderVideos();
