const videos = [
 {id:'dQw4w9WgXcQ',title:'The art of starting before you feel ready',creator:'Maya Chen',channel:'The Slow Down',views:'2.4M views',date:'3 days ago',duration:'12:48',category:'Design',description:'A thoughtful field guide to making space for better work, better ideas, and a little more courage.',avatar:'https://i.pravatar.cc/80?img=47',thumb:'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=900&q=80'},
 {id:'9bZkp7q19s4',title:'I built a tiny house in the mountains',creator:'Noah Williams',channel:'Field Notes',views:'891K views',date:'1 week ago',duration:'18:21',category:'Travel',description:'One year, one empty plot, and a lot of lessons about building a life with less noise.',avatar:'https://i.pravatar.cc/80?img=12',thumb:'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=900&q=80'},
 {id:'5JnMutdy6Yw',title:'The future of AI is more human than you think',creator:'Ari Patel',channel:'Signal / Noise',views:'1.1M views',date:'5 days ago',duration:'24:05',category:'Technology',description:'A clear, optimistic look at the tools changing how we create, work, and connect.',avatar:'https://i.pravatar.cc/80?img=32',thumb:'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80'},
 {id:'kJQP7kiw5Fk',title:'How I plan my week without burning out',creator:'Lena Ortiz',channel:'Sunday Studio',views:'430K views',date:'2 weeks ago',duration:'09:42',category:'Wellness',description:'A gentle weekly reset for people who want to do meaningful work without running on empty.',avatar:'https://i.pravatar.cc/80?img=49',thumb:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80'},
 {id:'3PHXvlpOkf4',title:'Tokyo at 5am: a quiet city guide',creator:'Kenji Watanabe',channel:'After Hours',views:'678K views',date:'4 days ago',duration:'15:16',category:'Travel',description:'The city before the crowds: coffee, train lines, and the best light in Tokyo.',avatar:'https://i.pravatar.cc/80?img=11',thumb:'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=900&q=80'},
 {id:'F9UG9XX9FIA',title:'The playlist that changed my year',creator:'Nia Rivers',channel:'Good Company',views:'2.8M views',date:'1 month ago',duration:'31:08',category:'Music',description:'Twenty songs, five memories, and one very good year in review.',avatar:'https://i.pravatar.cc/80?img=44',thumb:'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=900&q=80'},
 {id:'mFQP7N2pE4g',title:'A practical guide to making things beautiful',creator:'Studio Forma',channel:'Studio Forma',views:'944K views',date:'6 days ago',duration:'20:10',category:'Design',description:'The small decisions that make a big difference in product, space, and visual design.',avatar:'https://i.pravatar.cc/80?img=5',thumb:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=80'},
 {id:'Hzevd8l3x7M',title:'Why everyone is talking about indie games',creator:'Pixel Common',channel:'Pixel Common',views:'1.7M views',date:'3 weeks ago',duration:'14:33',category:'Gaming',description:'The tiny teams, big ideas, and strange new worlds behind the indie game renaissance.',avatar:'https://i.pravatar.cc/80?img=68',thumb:'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=900&q=80'}
];
const categories=['All','Design','Technology','Travel','Music','Wellness','Gaming','Live'];
const state={section:'home',category:'All',query:'',liked:false,subscribed:false,visible:8};
const $=id=>document.getElementById(id);
function renderCategories(){ $('categoryRow').innerHTML=categories.map(c=>`<button class="category-btn ${state.category===c?'active':''}" data-category="${c}">${c}</button>`).join(''); document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;renderCategories();renderVideos()}); }
function filtered(){let list=videos;if(state.category!=='All')list=list.filter(v=>v.category===state.category);if(state.query)list=list.filter(v=>(v.title+' '+v.creator+' '+v.category).toLowerCase().includes(state.query.toLowerCase()));return list;}
function renderVideos(){const list=filtered().slice(0,state.visible);$('videoGrid').innerHTML=list.length?list.map(v=>`<article class="video-card" data-video="${v.id}"><div class="thumbnail"><img loading="lazy" src="${v.thumb}" alt="${v.title}"><span class="duration">${v.duration}</span></div><div class="video-details"><img class="creator-avatar" src="${v.avatar}" alt=""><div><h3 class="video-title">${v.title}</h3><span class="channel-name">${v.channel}</span><span class="video-meta">${v.views} · ${v.date}</span></div></div></article>`).join(''):`<div class="empty-state"><h3>No videos found</h3><p>Try another search or topic.</p></div>`;document.querySelectorAll('.video-card').forEach(card=>card.onclick=()=>openPlayer(videos.find(v=>v.id===card.dataset.video)));}
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200);}
function openPlayer(video){$('videoFrame').src=`https://www.youtube.com/embed/${video.id}?autoplay=1&rel=0`;$('playerTitle').textContent=video.title;$('playerStats').textContent=`${video.channel} · ${video.views} · ${video.date}`;$('playerDescription').textContent=video.description;$('playerModal').classList.add('active');$('playerModal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}
function closePlayer(){$('videoFrame').src='';$('playerModal').classList.remove('active');$('playerModal').setAttribute('aria-hidden','true');document.body.style.overflow='';}
function setSection(section){state.section=section;document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.section===section));const titles={home:['Your daily mix','Watch next'],shorts:['Quick hits','Shorts'],subscriptions:['From your channels','Subscriptions'],history:['Keep watching','History'],liked:['Your favorites','Liked videos'],music:['Fresh sounds','Music'],gaming:['Press play','Gaming'],live:['Happening now','Live']};const [kicker,title]=titles[section]||titles.home;$('sectionKicker').textContent=kicker;$('sectionTitle').textContent=title;$('heroBanner').style.display=section==='home'?'flex':'none';state.category=section==='home'?'All':section==='shorts'?'All':section[0].toUpperCase()+section.slice(1);if(!categories.includes(state.category))state.category='All';renderCategories();renderVideos();$('sidebar').classList.remove('open');$('overlay').classList.remove('open');}
function search(){state.query=$('searchInput').value.trim();state.section='home';$('suggestions').hidden=true;$('sectionKicker').textContent=state.query?'Search results':'Your daily mix';$('sectionTitle').textContent=state.query?`Results for “${state.query}”`:'Watch next';renderVideos();}
$('searchForm').onsubmit=e=>{e.preventDefault();search()};$('searchInput').oninput=e=>{const q=e.target.value.trim();if(!q){$('suggestions').hidden=true;return}const matches=videos.filter(v=>v.title.toLowerCase().includes(q.toLowerCase())||v.creator.toLowerCase().includes(q.toLowerCase())).slice(0,3);$('suggestions').innerHTML=matches.map(v=>`<button class="suggestion" data-suggest="${v.title}"><i class="fas fa-arrow-trend-up"></i> ${v.title}</button>`).join('');$('suggestions').hidden=!matches.length;document.querySelectorAll('[data-suggest]').forEach(b=>b.onclick=()=>{$('searchInput').value=b.dataset.suggest;search()})};$('menuBtn').onclick=()=>{$('sidebar').classList.toggle('open');$('overlay').classList.toggle('open')};$('overlay').onclick=()=>{$('sidebar').classList.remove('open');$('overlay').classList.remove('open')};$('closePlayer').onclick=closePlayer;$('playerModal').onclick=e=>{if(e.target===$('playerModal'))closePlayer()};document.onkeydown=e=>{if(e.key==='Escape')closePlayer()};document.querySelectorAll('.nav-item').forEach(n=>n.onclick=()=>setSection(n.dataset.section));$('brand').onclick=()=>setSection('home');$('heroBtn').onclick=()=>{state.category='All';renderCategories();renderVideos();$('sectionTitle').scrollIntoView({behavior:'smooth'})};$('viewAllBtn').onclick=()=>{$('videoGrid').scrollIntoView({behavior:'smooth'})};$('loadMore').onclick=()=>{state.visible+=4;renderVideos();toast('More videos loaded')};$('playerSubscribe').onclick=()=>{state.subscribed=!state.subscribed;$('playerSubscribe').textContent=state.subscribed?'Subscribed':'Subscribe';toast(state.subscribed?'You are now subscribed':'Subscription removed')};$('likeBtn').onclick=()=>{state.liked=!state.liked;$('likeBtn').classList.toggle('liked',state.liked);$('likeBtn').innerHTML=state.liked?'<i class="fas fa-thumbs-up"></i> <span>Liked</span>':'<i class="far fa-thumbs-up"></i> <span>Like</span>';toast(state.liked?'Added to liked videos':'Removed from liked videos')};$('notificationBtn').onclick=()=>toast('You are all caught up');$('createBtn').onclick=()=>toast('Creator tools are coming soon');$('profileBtn').onclick=()=>toast('Profile menu coming soon');renderCategories();renderVideos();
